const PROCESSING_IMG_EXTS = ["png", "gif", "jpg", "jpeg"];
const INSPECTING_IMG_EXTS = [...PROCESSING_IMG_EXTS, "webp"]
const DIALOG_PROCESSING_EXT_FILTERS = [
  {
    name: "Images",
    extensions: PROCESSING_IMG_EXTS,
  },
];
const DIALOG_INSPECTING_EXT_FILTERS = [
  {
    name: "Images",
    extensions: INSPECTING_IMG_EXTS,
  },
];

const GIF_DELAY_DECIMAL_PRECISION = 2;
const APNG_DELAY_DECIMAL_PRECISION = 3;

module.exports = {
  PROCESSING_IMG_EXTS: PROCESSING_IMG_EXTS,
  INSPECTING_IMG_EXTS: INSPECTING_IMG_EXTS,
  DIALOG_INSPECTING_EXT_FILTERS: DIALOG_INSPECTING_EXT_FILTERS,
  DIALOG_PROCESSING_EXT_FILTERS: DIALOG_PROCESSING_EXT_FILTERS,
  GIF_DELAY_DECIMAL_PRECISION: GIF_DELAY_DECIMAL_PRECISION,
  APNG_DELAY_DECIMAL_PRECISION: APNG_DELAY_DECIMAL_PRECISION,
}
