const { Enumeration } = require('./enum.js');

/**
 * Class containing the summary of a preview image properties.
 */
class PreviewImageSummary {
  constructor(width, height, fileSize, isAnimated, frameCount, averageFPS, averageDelay, averageDuration, loopCount, format) {
    this.width = width;
    this.height = height;
    this.fileSize = fileSize;
    this.isAnimated = isAnimated;
    this.frameCount = frameCount;
    this.averageFPS = averageFPS;
    this.averageDelay = averageDelay;
    this.averageDuration = averageDuration;
    this.loopCount = loopCount;
    this.format = format;
  }

  get dimensionString() {
    return `${this.width} x ${this.height}`;
  }

  toSummaryText() {
    let text = `Dimensions: ${this.dimensionString}\n` +
    `File size: ${this.fileSize}\n` +
    `Total frames: ${this.frameCount}\n` +
    `FPS: ${this.averageFPS}\n` +
    `Delay: ${this.averageDelay} ms\n` +
    `Duration: ${this.averageDuration} seconds\n` +
    `Loop count: ${this.loopCount}\n` +
    `Format: ${this.format}`;
    return text;
  }
}

class PreviewImageSaveNameBehaviour extends Enumeration {
  static AutoGenerated = new PreviewImageSaveNameBehaviour(
    "auto_generated", "Auto-generated", "Automatically generated by TridentFrame with a timestamp and random characters.")
  static FromNameField = new PreviewImageSaveNameBehaviour(
    "from_name_field", "From Name field", "Take the name of the preview image from any available Name field in the current Panel.")
  static OpenWindowDialog = new PreviewImageSaveNameBehaviour(
    "open_window_dialog", "Open window dialog", "Open a save window dialog to manually name the preview image.")
  constructor(name, label, description=""){
    super(name, label, description);
  }
}

export { 
  PreviewImageSummary,
  PreviewImageSaveNameBehaviour,
}