const PROCESSING_IMG_EXTS = ["png", "gif", "jpg", "jpeg"];
const INSPECTING_IMG_EXTS = [...PROCESSING_IMG_EXTS, "webp"]
const DIALOG_PROCESSING_EXT_FILTERS = [
  {
    name: "Images",
    extensions: PROCESSING_IMG_EXTS,
  },
];
const DIALOG_INSPECTING_EXT_FILTERS = [
  {
    name: "Images",
    extensions: INSPECTING_IMG_EXTS,
  },
];


module.exports = {
  PROCESSING_IMG_EXTS: PROCESSING_IMG_EXTS,
  INSPECTING_IMG_EXTS: INSPECTING_IMG_EXTS,
  DIALOG_INSPECTING_EXT_FILTERS: DIALOG_INSPECTING_EXT_FILTERS,
  DIALOG_PROCESSING_EXT_FILTERS: DIALOG_PROCESSING_EXT_FILTERS,
}
